import type {
  Patient,
  Prescription,
  Appointment,
  InventoryItem,
  Staff,
  NursingNote,
  Bed,
  SystemSettings,
  AnalyticsData,
  Notification,
} from "./types"

export const mockPatients: Patient[] = [
  {
    id: "1",
    name: "John Smith",
    age: 45,
    gender: "male",
    phone: "+1-555-0123",
    email: "john.smith@email.com",
    address: "123 Main St, City, State 12345",
    diagnosis: "Hypertension",
    assignedDoctor: "Dr. Sarah Johnson",
    assignedBed: "A-101",
    vitals: {
      bloodPressure: "140/90",
      heartRate: 78,
      temperature: 98.6,
      oxygenSaturation: 98,
    },
    history: ["Previous heart surgery (2020)", "Diabetes Type 2"],
    admissionDate: new Date("2024-01-15"),
    status: "admitted",
    documents: [
      {
        id: "doc1",
        patientId: "1",
        name: "Blood Test Results",
        type: "lab-report",
        uploadDate: new Date("2024-01-16"),
        uploadedBy: "Dr. Sarah Johnson",
        fileSize: "2.3 MB",
        url: "/documents/blood-test-john.pdf",
      },
    ],
  },
  {
    id: "2",
    name: "Emily Davis",
    age: 32,
    gender: "female",
    phone: "+1-555-0124",
    email: "emily.davis@email.com",
    address: "456 Oak Ave, City, State 12345",
    diagnosis: "Pneumonia",
    assignedDoctor: "Dr. Michael Chen",
    assignedBed: "B-205",
    vitals: {
      bloodPressure: "120/80",
      heartRate: 85,
      temperature: 101.2,
      oxygenSaturation: 95,
    },
    history: ["Asthma since childhood"],
    admissionDate: new Date("2024-01-18"),
    status: "critical",
  },
  {
    id: "3",
    name: "Robert Wilson",
    age: 67,
    gender: "male",
    phone: "+1-555-0125",
    address: "789 Pine St, City, State 12345",
    diagnosis: "Cardiac Arrhythmia",
    assignedDoctor: "Dr. Sarah Johnson",
    assignedBed: "C-301",
    vitals: {
      bloodPressure: "160/95",
      heartRate: 92,
      temperature: 98.4,
      oxygenSaturation: 97,
    },
    history: ["Myocardial infarction (2019)", "High cholesterol"],
    admissionDate: new Date("2024-01-20"),
    status: "admitted",
  },
]

export const mockNursingNotes: NursingNote[] = [
  {
    id: "note1",
    patientId: "1",
    patientName: "John Smith",
    nurseId: "nurse1",
    nurseName: "Jennifer Brown",
    shift: "morning",
    type: "medication",
    content: "Administered Lisinopril 10mg at 8:00 AM. Patient tolerated well, no adverse reactions observed.",
    timestamp: new Date("2024-01-22T08:00:00"),
    priority: "medium",
    tags: ["medication", "blood-pressure"],
  },
  {
    id: "note2",
    patientId: "2",
    patientName: "Emily Davis",
    nurseId: "nurse1",
    nurseName: "Jennifer Brown",
    shift: "afternoon",
    type: "vitals",
    content: "Temperature elevated to 101.5°F. Administered cooling measures. Oxygen saturation stable at 95%.",
    timestamp: new Date("2024-01-22T14:30:00"),
    priority: "high",
    tags: ["fever", "vitals", "oxygen"],
  },
  {
    id: "note3",
    patientId: "1",
    patientName: "John Smith",
    nurseId: "nurse2",
    nurseName: "Maria Garcia",
    shift: "night",
    type: "observation",
    content: "Patient resting comfortably. No complaints of chest pain. Vital signs stable throughout the night.",
    timestamp: new Date("2024-01-22T22:00:00"),
    priority: "low",
    tags: ["observation", "stable"],
  },
]

export const mockBeds: Bed[] = [
  {
    id: "bed1",
    number: "A-101",
    ward: "Cardiology",
    floor: 1,
    type: "general",
    status: "occupied",
    patientId: "1",
    patientName: "John Smith",
    assignedNurse: "Jennifer Brown",
    lastCleaned: new Date("2024-01-22T06:00:00"),
    features: ["Cardiac Monitor", "Oxygen Supply"],
  },
  {
    id: "bed2",
    number: "A-102",
    ward: "Cardiology",
    floor: 1,
    type: "general",
    status: "available",
    lastCleaned: new Date("2024-01-22T10:00:00"),
    features: ["Cardiac Monitor", "Oxygen Supply"],
  },
  {
    id: "bed3",
    number: "B-205",
    ward: "Pulmonology",
    floor: 2,
    type: "icu",
    status: "occupied",
    patientId: "2",
    patientName: "Emily Davis",
    assignedNurse: "Jennifer Brown",
    lastCleaned: new Date("2024-01-22T06:00:00"),
    features: ["Ventilator", "Cardiac Monitor", "Oxygen Supply", "IV Pump"],
  },
  {
    id: "bed4",
    number: "C-301",
    ward: "General Medicine",
    floor: 3,
    type: "private",
    status: "occupied",
    patientId: "3",
    patientName: "Robert Wilson",
    assignedNurse: "Maria Garcia",
    lastCleaned: new Date("2024-01-22T08:00:00"),
    features: ["TV", "Private Bathroom", "Cardiac Monitor"],
  },
  {
    id: "bed5",
    number: "E-101",
    ward: "Emergency",
    floor: 1,
    type: "emergency",
    status: "available",
    lastCleaned: new Date("2024-01-22T12:00:00"),
    features: ["Defibrillator", "Oxygen Supply", "IV Pump", "Cardiac Monitor"],
  },
]

export const mockSystemSettings: SystemSettings = {
  hospital: {
    name: "MedSync General Hospital",
    address: "123 Healthcare Blvd, Medical City, MC 12345",
    phone: "+1-555-HOSPITAL",
    email: "info@medsync-hospital.com",
  },
  notifications: {
    emailEnabled: true,
    smsEnabled: true,
    pushEnabled: true,
  },
  security: {
    sessionTimeout: 30,
    passwordPolicy: {
      minLength: 8,
      requireSpecialChars: true,
      requireNumbers: true,
    },
    twoFactorEnabled: false,
  },
  backup: {
    autoBackup: true,
    backupFrequency: "daily",
    retentionDays: 30,
  },
}

export const mockAnalyticsData: AnalyticsData = {
  patientFlow: [
    { admissions: 15, discharges: 12, transfers: 3, date: new Date("2024-01-15") },
    { admissions: 18, discharges: 14, transfers: 2, date: new Date("2024-01-16") },
    { admissions: 22, discharges: 16, transfers: 4, date: new Date("2024-01-17") },
    { admissions: 19, discharges: 18, transfers: 1, date: new Date("2024-01-18") },
    { admissions: 25, discharges: 20, transfers: 5, date: new Date("2024-01-19") },
    { admissions: 16, discharges: 22, transfers: 2, date: new Date("2024-01-20") },
    { admissions: 20, discharges: 15, transfers: 3, date: new Date("2024-01-21") },
  ],
  departmentStats: [
    { department: "Cardiology", patients: 45, staff: 12, utilization: 85 },
    { department: "Pulmonology", patients: 32, staff: 8, utilization: 78 },
    { department: "Emergency", patients: 28, staff: 15, utilization: 92 },
    { department: "General Medicine", patients: 38, staff: 10, utilization: 76 },
    { department: "Pediatrics", patients: 22, staff: 6, utilization: 68 },
  ],
  financialMetrics: [
    { revenue: 125000, expenses: 95000, profit: 30000, month: "Jan 2024" },
    { revenue: 132000, expenses: 98000, profit: 34000, month: "Feb 2024" },
    { revenue: 128000, expenses: 92000, profit: 36000, month: "Mar 2024" },
    { revenue: 145000, expenses: 105000, profit: 40000, month: "Apr 2024" },
    { revenue: 138000, expenses: 100000, profit: 38000, month: "May 2024" },
    { revenue: 142000, expenses: 103000, profit: 39000, month: "Jun 2024" },
  ],
  inventoryTrends: [
    { category: "Medicine", usage: 85, cost: 25000, month: "Jan" },
    { category: "Equipment", usage: 92, cost: 45000, month: "Jan" },
    { category: "Supplies", usage: 78, cost: 15000, month: "Jan" },
    { category: "Medicine", usage: 88, cost: 27000, month: "Feb" },
    { category: "Equipment", usage: 89, cost: 42000, month: "Feb" },
    { category: "Supplies", usage: 82, cost: 16000, month: "Feb" },
  ],
}

export const mockNotifications: Notification[] = [
  {
    id: "notif1",
    title: "Critical Patient Alert",
    message: "Emily Davis requires immediate attention - fever spike detected",
    type: "error",
    role: "nurse",
    read: false,
    createdAt: new Date("2024-01-22T14:35:00"),
    actionUrl: "/dashboard/nurse/patients",
  },
  {
    id: "notif2",
    title: "Low Stock Alert",
    message: "Paracetamol is out of stock - immediate restocking required",
    type: "warning",
    role: "pharmacist",
    read: false,
    createdAt: new Date("2024-01-22T10:00:00"),
    actionUrl: "/dashboard/pharmacist/inventory",
  },
  {
    id: "notif3",
    title: "Prescription Approved",
    message: "Prescription for John Smith has been approved and is ready for dispensing",
    type: "success",
    role: "doctor",
    read: true,
    createdAt: new Date("2024-01-22T09:15:00"),
    actionUrl: "/dashboard/doctor/prescriptions",
  },
]

export const mockPrescriptions: Prescription[] = [
  {
    id: "1",
    patientId: "1",
    patientName: "John Smith",
    doctorId: "doc1",
    doctorName: "Dr. Sarah Johnson",
    medicines: [
      {
        name: "Lisinopril",
        dosage: "10mg",
        frequency: "Once daily",
        duration: "30 days",
      },
      {
        name: "Metformin",
        dosage: "500mg",
        frequency: "Twice daily",
        duration: "30 days",
      },
    ],
    status: "pending",
    notes: "Monitor blood pressure regularly",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    patientId: "2",
    patientName: "Emily Davis",
    doctorId: "doc2",
    doctorName: "Dr. Michael Chen",
    medicines: [
      {
        name: "Azithromycin",
        dosage: "250mg",
        frequency: "Once daily",
        duration: "5 days",
      },
      {
        name: "Albuterol Inhaler",
        dosage: "2 puffs",
        frequency: "As needed",
        duration: "30 days",
      },
    ],
    status: "approved",
    createdAt: new Date("2024-01-18"),
    processedAt: new Date("2024-01-18"),
    processedBy: "Pharmacist John",
  },
]

export const mockAppointments: Appointment[] = [
  {
    id: "1",
    patientId: "1",
    patientName: "John Smith",
    doctorId: "doc1",
    doctorName: "Dr. Sarah Johnson",
    date: new Date("2024-01-25"),
    time: "10:00 AM",
    type: "follow-up",
    status: "scheduled",
    notes: "Blood pressure check",
  },
  {
    id: "2",
    patientId: "3",
    patientName: "Robert Wilson",
    doctorId: "doc1",
    doctorName: "Dr. Sarah Johnson",
    date: new Date("2024-01-26"),
    time: "2:00 PM",
    type: "consultation",
    status: "scheduled",
    notes: "Cardiac evaluation",
  },
]

export const mockInventory: InventoryItem[] = [
  {
    id: "1",
    name: "MRI Machine",
    category: "equipment",
    quantity: 2,
    unit: "units",
    location: "Radiology Department",
    lastUpdated: new Date("2024-01-20"),
    minThreshold: 1,
    status: "available",
  },
  {
    id: "2",
    name: "Surgical Gloves",
    category: "supplies",
    quantity: 50,
    unit: "boxes",
    location: "Supply Room A",
    lastUpdated: new Date("2024-01-22"),
    minThreshold: 20,
    status: "low-stock",
  },
  {
    id: "3",
    name: "Paracetamol",
    category: "medicine",
    quantity: 0,
    unit: "bottles",
    location: "Pharmacy",
    lastUpdated: new Date("2024-01-23"),
    minThreshold: 10,
    status: "out-of-stock",
  },
]

export const mockStaff: Staff[] = [
  {
    id: "1",
    name: "Dr. Sarah Johnson",
    email: "sarah.johnson@medsync.com",
    role: "doctor",
    specialization: "Cardiology",
    department: "Cardiology",
    phone: "+1-555-0201",
    status: "active",
    joinDate: new Date("2020-03-15"),
  },
  {
    id: "2",
    name: "Dr. Michael Chen",
    email: "michael.chen@medsync.com",
    role: "doctor",
    specialization: "Pulmonology",
    department: "Internal Medicine",
    phone: "+1-555-0202",
    status: "active",
    joinDate: new Date("2019-08-20"),
  },
  {
    id: "3",
    name: "Nurse Jennifer Brown",
    email: "jennifer.brown@medsync.com",
    role: "nurse",
    department: "General Ward",
    phone: "+1-555-0203",
    status: "active",
    joinDate: new Date("2021-01-10"),
  },
]

// AI Insights Mock Data
export const mockAIInsights = {
  opdPrediction: {
    title: "Predicted OPD Load for Next 7 Days",
    data: [
      { day: "Mon", patients: 45 },
      { day: "Tue", patients: 52 },
      { day: "Wed", patients: 38 },
      { day: "Thu", patients: 61 },
      { day: "Fri", patients: 48 },
      { day: "Sat", patients: 35 },
      { day: "Sun", patients: 28 },
    ],
    insight: "Thursday expected to be the busiest day with 61 patients",
  },
  commonConditions: {
    title: "Common Conditions This Week",
    data: [
      { condition: "Hypertension", count: 23, percentage: 35 },
      { condition: "Diabetes", count: 18, percentage: 27 },
      { condition: "Respiratory Issues", count: 15, percentage: 23 },
      { condition: "Cardiac Issues", count: 10, percentage: 15 },
    ],
    insight: "Hypertension cases increased by 15% compared to last week",
  },
  topDoctors: {
    title: "Top Performing Doctors",
    data: [
      { name: "Dr. Sarah Johnson", patients: 45, rating: 4.9, department: "Cardiology" },
      { name: "Dr. Michael Chen", patients: 38, rating: 4.8, department: "Pulmonology" },
      { name: "Dr. Lisa Wang", patients: 42, rating: 4.7, department: "Internal Medicine" },
    ],
    insight: "Dr. Sarah Johnson maintains highest patient satisfaction",
  },
}
